name: Test compilation, run tests and build

on:
    pull_request

jobs:
  perl-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.32'
          - 'latest'
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Test compilation
        run: |
          find lib/ -name *.pm | parallel perl -I ./lib
      - name: Regular tests
        run: |
          cpanm --installdeps --notest .
          perl Makefile.PL
          make
          make test
      - name: Test cpanm deploy
        run: |
          make manifest
          make dist
          cpan-upload --dry-run YuiRestClient-*.tar.gz -u QEYAST -p test
